doctrine:
    dbal:
        # configure these for your database server
        # use postgresql for PostgreSQL
        # use sqlite for SQLite
        driver: 'mysql'
        server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            json:     Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # cache start
#        second_level_cache:
#            regions:
#                entity_that_rarely_changes:
#                    lifetime: 86400 # 1 day
#                    cache_driver:
#                        type: service
#                        id: doctrine.result_cache_provider
#
#        result_cache_driver:
#            type: service
#            id: doctrine.result_cache_provider
        # cache end
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            SonataUserBundle: ~
            FOSUserBundle: ~
            SonataMediaBundle: ~
            ApplicationSonataMediaBundle: ~
            SonataClassificationBundle: ~
            ApplicationSonataClassificationBundle: ~

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'

#doctrine_cache:
#    providers:
#        metadata_cache_driver:
#            type: apc
#        query_cache_driver:
#            type: apc
#        result_cache_driver:
#            type: apc