parameters:
    sonata_media:
        providers:
            file:
                allowed_extensions:
                    - pdf
                    - rar
#    sonata_media.providers.file.allowed_mime_types:
sonata_media:
    default_context: default
    force_disable_category: true
    admin_format:
        width: 200
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                admin: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        sonata_collection:
            providers:
                - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
                - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        admin:
            providers:
                - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        devices:
            providers:
                - sonata.media.provider.image

            formats:
                preview: { width: 320, quality: 100, format: png }

        tv_plan:
            providers:
                - sonata.media.provider.image

        slider:
            providers:
                - sonata.media.provider.image
            formats:
                preview: { width: 1960, height: 1000, quality: 100 }
                original: { width: 2000, quality: 100 }

        news:
            providers:
                - sonata.media.provider.image
            formats:
                preview: { width: 858, height: 504, quality: 100, resizer: app.sonata.media.crop_resizer }

        developers:
            providers:
                - sonata.media.provider.image
            formats:
                preview: { width: 858, height: 504, quality: 100, resizer: app.sonata.media.crop_resizer }

        documents:
            providers:
                - sonata.media.provider.file

        license:
            providers:
                - sonata.media.provider.image
            formats:
                preview: { width: 693, height: 980, quality: 70}

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false

    class:
        media: App\Application\Sonata\MediaBundle\Entity\Media
        gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category: App\Application\Sonata\ClassificationBundle\Entity\Category

    db_driver: doctrine_orm

    resizer:
        simple:
            mode: outbound
