twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataMedia/Form/media_widgets.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
        - 'admin/widgets/custom_widgets.html.twig'
    globals:
        header_options: '@App\ViewOptions\HeaderOptions'
