<?php

declare(strict_types=1);

namespace App\Controller;

use Sonata\AdminBundle\Controller\CRUDController;

final class NewsItemAdminController extends CRUDController
{

    public function editAction($id = null)
    {
        return parent::editAction($id); // TODO: Change the autogenerated stub
    }
}
