#index:
#    path: /
#    controller: App\Controller\DefaultController::index
sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

products:
    resource: App\Controller\ProductsController
    type: annotation
    prefix: /

#news:
#    resource: App\Controller\NewsController
#    type: annotation
#    prefix: /news

news:
    resource: 'routes/news.yaml'
    prefix: /news

blog:
    resource: 'routes/blog.yaml'
    prefix: /blog

artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     annotation
    prefix:   /admin/filemanager