<?php

namespace App\Application\Sonata\ClassificationBundle\Entity;

use Sonata\ClassificationBundle\Entity\BaseCategory as BaseCategory;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use JMS\Serializer\Annotation as JMS;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */

/**
 * Class Category
 * @package App\Application\Sonata\ClassificationBundle\Entity
 * @UniqueEntity("code", message="Код должен быть уникальным")
 */
class Category extends BaseCategory
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @Assert\Regex(pattern="/^[A-Za-z_0-9]+$/")
     */
    protected $code;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    private $slugPath;

    public function getSlugPath()
    {
        return $this->slugPath;
    }

    public function setSlugPath(){
        $parent = $this->getParent();
        if(null == $parent)
            $this->slugPath = $this->getSlug();
        else
            $this->slugPath = $parent->getSlugPath().'/'.$this->getSlug();

    }

    public function setSlug($slug)
    {
        parent::setSlug($slug);
        $this->setSlugPath();
    }

    /**
     * @return mixed
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * @param mixed $code
     */
    public function setCode($code): void
    {
        $this->code = $code;
    }





}
