<?php

namespace App\Application\Sonata\ClassificationBundle\Entity;

use Sonata\ClassificationBundle\Entity\BaseCategory as BaseCategory;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Category extends BaseCategory
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    private $slugPath;

    public function getSlugPath()
    {
        return $this->slugPath;
    }

    public function setSlugPath(){
        $parent = $this->getParent();
        if(null == $parent)
            $this->slugPath = $this->getSlug();
        else
            $this->slugPath = $parent->getSlugPath().'/'.$this->getSlug();

    }

    public function setSlug($slug)
    {
        parent::setSlug($slug);
        $this->setSlugPath();
    }


}
