<?php


namespace App\Admin;


use App\Application\Sonata\ClassificationBundle\Entity\Category;
use App\Entity\AddressObject;
use App\Entity\InternetPlan;
use App\Entity\PricingType;
use App\Form\DataTransformer\HiddenEntityTransformer;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;

class InternetAdmin extends ProductAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        parent::configureFormFields($formMapper);

        $formMapper->tab('Основное')
                ->with('Product')
                    ->remove('category')
                    ->add('category', HiddenType::class, [
                        //'data' => $this->getCategoryManager()->findOneBy(['code' => 'internet_basic']),
                    ])
                ->end()
                ->with('Интернет', ['class' => 'col-md-6'])
                    ->add('speed', IntegerType::class, [
                        'label' => 'Скорость'
                    ])
                ->end()
//                ->with('Адреса', ['class' => 'col-md-6'])
//                    ->add('assigned_address_objects', EntityType::class, [
//                        'class' => AddressObject::class,
//                        'multiple' => true,
//                        'expanded' => true,
//                        'label' => false,
//                    ])
//                ->end()
                ->with('Ценовая группа', ['class' => 'col-md-6'])
                    ->add('pricingType', EntityType::class, [
                        'class' => PricingType::class,
                        'choice_label' => function ($item) {
                            dump($item);
                            return $item->getName();
                        },
                    ])
                ->end()
            ->end()
        ;

        dump($this->getSubject()->getPricingType());

        $formMapper->get('category')
            ->addModelTransformer(
                new HiddenEntityTransformer(
                    $this->getConfigurationPool()->getContainer()->get('doctrine.orm.entity_manager'),
                    Category::class,
                    'id'
                )
            )
        ;
    }

    public function prePersist($object)
    {
        /**
         * @var InternetPlan $object
         */
        $object->setCategory(
            $this->getCategoryManager()->findOneBy(['code' => 'internet_basic'])
        );
        parent::prePersist($object); // TODO: Change the autogenerated stub
    }


    protected function getRootCategoryCode()
    {
        return 'internet';
    }


}